import * as THREE from 'three';
import { VRButton } from 'https://unpkg.com/three@0.166.1/examples/jsm/webxr/VRButton.js';

const canvas=document.querySelector('#game'), intro=document.querySelector('#intro'), hud=document.querySelector('#hud');
const renderer=new THREE.WebGLRenderer({canvas,antialias:true,powerPreference:'high-performance'});
renderer.setPixelRatio(Math.min(devicePixelRatio,1.7)); renderer.setSize(innerWidth,innerHeight); renderer.shadowMap.enabled=true; renderer.shadowMap.type=THREE.PCFSoftShadowMap; renderer.xr.enabled=true; renderer.toneMapping=THREE.ACESFilmicToneMapping; renderer.toneMappingExposure=1.15;
const scene=new THREE.Scene(); scene.background=new THREE.Color(0x080a0d); scene.fog=new THREE.FogExp2(0x0b1117,.011);
const camera=new THREE.PerspectiveCamera(72,innerWidth/innerHeight,.08,500); camera.position.set(0,2,13);
const rig=new THREE.Group(); rig.add(camera); scene.add(rig);
const hemi=new THREE.HemisphereLight(0x9edfff,0x1a1614,1.5); scene.add(hemi);
const sun=new THREE.DirectionalLight(0xffd5c2,3); sun.position.set(-18,28,12); sun.castShadow=true; sun.shadow.mapSize.set(1024,1024); scene.add(sun);
const redLight=new THREE.PointLight(0xff3329,22,55,2); redLight.position.set(0,6,-32); scene.add(redLight);
const metal=new THREE.MeshStandardMaterial({color:0x30383d,roughness:.62,metalness:.75});
const dark=new THREE.MeshStandardMaterial({color:0x101519,roughness:.72,metalness:.8});
const red=new THREE.MeshStandardMaterial({color:0xb40f18,roughness:.38,metalness:.65});
const glow=new THREE.MeshBasicMaterial({color:0x8ceaff});
const hostileGlow=new THREE.MeshBasicMaterial({color:0xff3b28});
const ground=new THREE.Mesh(new THREE.PlaneGeometry(520,520),new THREE.MeshStandardMaterial({color:0x11181c,roughness:.92,metalness:.05})); ground.rotation.x=-Math.PI/2; ground.receiveShadow=true; scene.add(ground);
const grid=new THREE.GridHelper(520,130,0x31454f,0x1b282e); grid.material.opacity=.3; grid.material.transparent=true; scene.add(grid);

function box(x,y,z,sx,sy,sz,mat=metal,rot=0){const m=new THREE.Mesh(new THREE.BoxGeometry(sx,sy,sz),mat);m.position.set(x,y,z);m.rotation.y=rot;m.castShadow=m.receiveShadow=true;scene.add(m);return m}
for(let i=0;i<46;i++){const a=(i%2?1:-1)*(12+Math.random()*55), z=-15-Math.random()*170, h=4+Math.random()*31, w=5+Math.random()*10; const b=box(a,h/2,z,w,h,5+Math.random()*9,i%5===0?red:dark,(Math.random()-.5)*.08); if(i%3===0){const win=new THREE.Mesh(new THREE.PlaneGeometry(w*.55,h*.65),new THREE.MeshBasicMaterial({color:0x71c5db,transparent:true,opacity:.18}));win.position.set(a+(a>0?-w/2-.01:w/2+.01),h*.52,z);win.rotation.y=a>0?-Math.PI/2:Math.PI/2;scene.add(win)}}
for(let i=0;i<34;i++){const x=(Math.random()-.5)*80,z=(Math.random()-.5)*220-45; const scrap=box(x,.3+Math.random(),z,.5+Math.random()*3,.3+Math.random()*1.2,.5+Math.random()*3,i%4?metal:red,Math.random()*6);scrap.rotation.z=Math.random()}
const rift=new THREE.Group(); const ring=new THREE.Mesh(new THREE.TorusGeometry(9,.27,12,64),new THREE.MeshBasicMaterial({color:0x4edfff,transparent:true,opacity:.76})); ring.scale.y=1.45; rift.add(ring); for(let i=0;i<3;i++){const r=new THREE.Mesh(new THREE.TorusGeometry(7-i*1.5,.055,6,64),new THREE.MeshBasicMaterial({color:i%2?0xef312f:0x8ceaff,transparent:true,opacity:.8}));r.scale.y=1.45;r.rotation.z=i*.6;rift.add(r)} rift.position.set(0,11,-55);scene.add(rift);
const stars=new THREE.BufferGeometry(), pts=[];for(let i=0;i<800;i++)pts.push((Math.random()-.5)*300,Math.random()*90,(Math.random()-.5)*400);stars.setAttribute('position',new THREE.Float32BufferAttribute(pts,3));scene.add(new THREE.Points(stars,new THREE.PointsMaterial({color:0x9edfff,size:.12,transparent:true,opacity:.48})));

const enemies=[], bolts=[], enemyBolts=[]; let kills=0,wave=1,energy=100,playing=false,vehicle=false,lastSpawn=0,noticeTimer=0;
function makeEnemy(){const g=new THREE.Group(); const torso=new THREE.Mesh(new THREE.BoxGeometry(1.5,2.1,.9),dark), chest=new THREE.Mesh(new THREE.BoxGeometry(1.05,.65,.98),red),head=new THREE.Mesh(new THREE.OctahedronGeometry(.55,0),metal);torso.position.y=1.9;chest.position.set(0,2.1,.5);head.position.y=3.45;g.add(torso,chest,head); for(const s of [-1,1]){const arm=new THREE.Mesh(new THREE.BoxGeometry(.45,2,.5),metal);arm.position.set(s*1,1.9,0);arm.rotation.z=-s*.12;g.add(arm);const leg=new THREE.Mesh(new THREE.BoxGeometry(.55,1.8,.7),dark);leg.position.set(s*.45,.35,0);g.add(leg);const eye=new THREE.Mesh(new THREE.BoxGeometry(.28,.08,.04),hostileGlow);eye.position.set(s*.16,3.55,.5);g.add(eye)} g.position.set((Math.random()-.5)*28,0,-52-Math.random()*30);g.scale.setScalar(.8+Math.random()*.32);g.userData={hp:2,lastShot:performance.now()+Math.random()*2200,speed:.012+Math.random()*.011};scene.add(g);enemies.push(g)}
function shoot(origin,direction,enemy=false){const m=new THREE.Mesh(new THREE.SphereGeometry(enemy?.11:.08,5,5),enemy?hostileGlow:glow);m.position.copy(origin);m.userData.vel=direction.clone().multiplyScalar(enemy?.22:.55);m.userData.life=260;scene.add(m);(enemy?enemyBolts:bolts).push(m)}
function fire(){if(!playing||energy<4)return;energy-=4; const dir=new THREE.Vector3();camera.getWorldDirection(dir);const p=new THREE.Vector3();camera.getWorldPosition(p);p.add(dir.clone().multiplyScalar(.8));shoot(p,dir);document.querySelector('#energy-bar').style.width=energy+'%'}
function transform(){if(!playing)return;vehicle=!vehicle;document.querySelector('#mode').textContent=vehicle?'VEHICLE MODE // BOOST':'BIPED MODE'; camera.position.y=vehicle?.95:2;showNotice(vehicle?'VEHICLE MODE':'BIPED MODE')}
function showNotice(t){const n=document.querySelector('#notice');n.textContent=t;n.classList.add('show');clearTimeout(noticeTimer);noticeTimer=setTimeout(()=>n.classList.remove('show'),1300)}

const clock=new THREE.Clock(),keys={};addEventListener('keydown',e=>{keys[e.code]=true;if(e.code==='KeyT')transform()});addEventListener('keyup',e=>keys[e.code]=false);addEventListener('mousedown',()=>{if(playing){if(document.pointerLockElement!==canvas)canvas.requestPointerLock();else fire()}});let yaw=0,pitch=0;addEventListener('mousemove',e=>{if(document.pointerLockElement===canvas&&!renderer.xr.isPresenting){yaw-=e.movementX*.002;pitch=Math.max(-1.25,Math.min(1.25,pitch-e.movementY*.002));rig.rotation.y=yaw;camera.rotation.x=pitch}});
function start(){playing=true;intro.classList.add('out');setTimeout(()=>intro.remove(),600);hud.hidden=false;showNotice('RIFT BREACH DETECTED');for(let i=0;i<5;i++)makeEnemy()}
document.querySelector('#play').onclick=()=>{start();canvas.requestPointerLock()};
const vrButton=VRButton.createButton(renderer,{optionalFeatures:['local-floor','bounded-floor']});document.querySelector('#vr-slot').appendChild(vrButton);renderer.xr.addEventListener('sessionstart',()=>{if(!playing)start()});
for(let i=0;i<2;i++){const c=renderer.xr.getController(i);c.addEventListener('selectstart',fire);c.addEventListener('squeezestart',transform);const laser=new THREE.Mesh(new THREE.CylinderGeometry(.004,.012,1.5,6),new THREE.MeshBasicMaterial({color:0x9feeff,transparent:true,opacity:.5}));laser.rotation.x=-Math.PI/2;laser.position.z=-.75;c.add(laser);rig.add(c)}
function updateControllers(dt){const session=renderer.xr.getSession();if(!session)return;for(const source of session.inputSources){if(!source.gamepad)continue;const a=source.gamepad.axes;if(a.length>=4){const speed=(vehicle?14:7)*dt;const forward=new THREE.Vector3();camera.getWorldDirection(forward);forward.y=0;forward.normalize();const right=new THREE.Vector3(forward.z,0,-forward.x);rig.position.addScaledVector(forward,-a[3]*speed);rig.position.addScaledVector(right,a[2]*speed)}}}
function update(){const dt=Math.min(clock.getDelta(),.035),t=performance.now();rift.rotation.z+=dt*.08;ring.material.opacity=.65+Math.sin(t*.004)*.15; if(!playing)return;
 if(!renderer.xr.isPresenting){const speed=(vehicle?18:8)*dt,forward=new THREE.Vector3(-Math.sin(yaw),0,-Math.cos(yaw)),right=new THREE.Vector3(Math.cos(yaw),0,-Math.sin(yaw));if(keys.KeyW)rig.position.addScaledVector(forward,speed);if(keys.KeyS)rig.position.addScaledVector(forward,-speed);if(keys.KeyA)rig.position.addScaledVector(right,-speed);if(keys.KeyD)rig.position.addScaledVector(right,speed)}else updateControllers(dt);
 rig.position.x=THREE.MathUtils.clamp(rig.position.x,-70,70);rig.position.z=THREE.MathUtils.clamp(rig.position.z,-170,35);energy=Math.min(100,energy+dt*7);document.querySelector('#energy-bar').style.width=energy+'%';
 if(t-lastSpawn>Math.max(850,2600-wave*140)&&enemies.length<7+wave){makeEnemy();lastSpawn=t}
 const playerPos=new THREE.Vector3();camera.getWorldPosition(playerPos);
 for(let i=enemies.length-1;i>=0;i--){const e=enemies[i],toPlayer=playerPos.clone().sub(e.position),dist=toPlayer.length();e.lookAt(playerPos.x,e.position.y,playerPos.z);if(dist>7)e.position.addScaledVector(toPlayer.normalize(),e.userData.speed*(vehicle?1.35:1));if(t-e.userData.lastShot>1600+Math.random()*1500&&dist<55){const p=e.position.clone().add(new THREE.Vector3(0,2.5,0));shoot(p,playerPos.clone().sub(p).normalize(),true);e.userData.lastShot=t}e.children[1].material.emissive?.setHex(Math.sin(t*.005+i)>.8?0x420000:0x000000)}
 for(let i=bolts.length-1;i>=0;i--){const b=bolts[i];b.position.add(b.userData.vel);b.userData.life--;let hit=false;for(let j=enemies.length-1;j>=0;j--){if(b.position.distanceTo(enemies[j].position.clone().add(new THREE.Vector3(0,1.8,0)))<1.35){enemies[j].userData.hp--;hit=true;if(enemies[j].userData.hp<=0){scene.remove(enemies[j]);enemies.splice(j,1);kills++;document.querySelector('#kills').textContent=String(kills).padStart(3,'0');if(kills%8===0){wave++;document.querySelector('#wave').textContent='WAVE '+String(wave).padStart(2,'0');showNotice('WAVE '+String(wave).padStart(2,'0'))}}break}}if(hit||b.userData.life<0){scene.remove(b);bolts.splice(i,1)}}
 for(let i=enemyBolts.length-1;i>=0;i--){const b=enemyBolts[i];b.position.add(b.userData.vel);b.userData.life--;if(b.position.distanceTo(playerPos)<.65){document.querySelector('#damage').style.opacity='.8';setTimeout(()=>document.querySelector('#damage').style.opacity='0',120);scene.remove(b);enemyBolts.splice(i,1);continue}if(b.userData.life<0){scene.remove(b);enemyBolts.splice(i,1)}}
}
renderer.setAnimationLoop(()=>{update();renderer.render(scene,camera)});
addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});
